apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: main-flask-network-policy
  namespace: my-app
spec:
  podSelector:
    matchLabels:
      app: main-flask
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0   
    ports:
    - protocol: TCP
      port: 80          
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ocr-service
    ports:
    - protocol: TCP
      port: 5000        
  - to:
    - podSelector:
        matchLabels:
          app: rag-service
    ports:
    - protocol: TCP
      port: 5050         
  - to:
    - podSelector:
        matchLabels:
          app: ocr-service
    ports:
    - protocol: TCP
      port: 5080
  - to:
    - podSelector:
        matchLabels:
          app: voice2text-service
    ports:
    - protocol: TCP
      port: 6000